[package]
name = "helium-wallet"
version = "1.7.12"
authors = ["Helium <info@helium.com>"]
edition = "2021"

description = "A Rust Helium Wallet library"
readme = "README.md"
keywords = ["helium", "blockchain", "wallet"]

homepage = "https://developer.helium.com/blockchain/blockchain-cli"
repository = "https://github.com/helium/helium-wallet-rs"

license = "Apache-2.0"

[[bin]]
name = "helium-wallet"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = "1"
thiserror = "1"
byteorder = "1.3.2"
dialoguer = "0.8"
sodiumoxide = "~0.2"
hex = "0.4"
hmac = "0.12"
sha2 = "0.10"
base64 = ">=0.21"
bs58 = "0"
reqwest = {version = "0", default-features=false, features=["rustls-tls"]}
pbkdf2 = {version = "0", default-features=false }
aes-gcm = "0"
shamirsecretsharing = {version="0.1.5", features=["have_libsodium"]}
lazy_static = "1"
rand = "0.8"
qr2term = "0.2"
serde =  "1"
serde_json = "1"
rust_decimal = {version = "1", features = ["serde-float"] }
rust_decimal_macros = "1"
h3o = "0"
rayon = "1"
angry-purple-tiger = "0"
clap = {version = "4", features = ["derive"]}
helium-crypto = { version = "0.6.3", features = ["multisig", "solana"]}
helium-proto = { git = "https://github.com/helium/proto", branch="master"}
data-credits = { git = "https://github.com/helium/helium-program-library", branch="master", features = [ "no-entrypoint" ]  }
lazy-distributor = { git = "https://github.com/helium/helium-program-library", branch="master", features = [ "no-entrypoint" ]  }
helium-entity-manager = { git = "https://github.com/helium/helium-program-library", branch="master", features = [ "no-entrypoint" ]  }
helium-sub-daos = { git = "https://github.com/helium/helium-program-library", branch="master", features = [ "no-entrypoint" ]  }
circuit-breaker = { git = "https://github.com/helium/helium-program-library", branch="master", features = [ "no-entrypoint" ]  }
spl-associated-token-account = "*"
bincode = "*"
pyth-sdk-solana = "0"
anchor-client = "0"
anchor-spl = "0"
tiny-bip39 = "0"
http = "0"
jsonrpc = "0"
