[package]
name = "helium-wallet"
version = "1.0.2"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = { version = "0.4"}
byteorder = "1.3.2"
structopt = "0.3.2"
dialoguer = "0.4.0"
bs58 = {version = "0.3.0", features=["check"]}
sodiumoxide = "0.2.5"
hmac = "0.7.1"
sha2 = "0.8.0"
pbkdf2 = {version = "0.3.0", default-features=false }
aead = "0.1.1"
aes-gcm = "0.1.0"
shamirsecretsharing = {version="0.1.4", features=["have_libsodium"]}
prettytable-rs = "0.6"
lazy_static = "1"
regex = "1"
qr2term = "0.1"
helium-api = { git = "https://github.com/helium/helium-api-rs"}
helium-proto = { git = "https://github.com/helium/proto" }
prost = "0.5"
ledger = "0.1.0"

# Add openssl-sys as a direct dependency so it can be cross compiled to
# x86_64-unknown-linux-musl using the "vendored" feature below
openssl-sys = "*"

[features]
# Force openssl-sys to staticly link in the openssl library. Necessary when
# cross compiling to x86_64-unknown-linux-musl.
vendored = ["openssl-sys/vendored"]