[package]
name = "helium-wallet"
version = "0.1.0"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
structopt = "0.3.2"
dialoguer = "0.4.0"
bs58 = {version = "0.3.0", features=["check"]}
sodiumoxide = "0.2.5"
hmac = "0.7.1"
sha2 = "0.8.0"
pbkdf2 = {version = "0.3.0", default-features=false }
aead = "0.1.1"
aes-gcm = "0.1.0"
shamirsecretsharing = {git = "https://github.com/dsprenkels/sss-rs", branch="master", features=["have_libsodium"]}
helium-api = { git = "https://github.com/helium/helium-api-rs"}
